### PR TITLE
[PR] Fixing black borders. 

### LINKED ISSUE #66: Chore: Compressed landscape (aspect) images add black border
At present the compressed images work fine until we have a wider image ...
https://jsfiddle.net/6t7p0eqc/7/

dwyl-imgup-compressed-images-add-black-border

<h1>
Original
</h1>

image

<h1>
Compressed:
</h1>

image

# Todo

+ [x] Document the setup of the image compressor in https://github.com/dwyl/imgup/tree/main/an_aws_sam_imgup-compressor adding _all_ the steps taken to deploy the app on `AWS`: https://github.com/dwyl/imgup#7-resizingcompressing-files
+ [x] Alter the `.resize` code that currently creates a `200x200` square:

https://github.com/dwyl/imgup/blob/a6596c6e2289d03d7b50d73b998db405fd9086ed/an_aws_sam_imgup-compressor/src/index.js#L20-L24

  + [x] Should only constrain in one dimension e.g: _only_ `width` or _only_ `height` 
  i.e. preserve the aspect ratio of images.

+ [x] Redeploy the `compressor` app on `AWS`. 
+ [x] Confirm that compressed images are preserving aspect ratio (not adding black border)

### LINKED ISSUE #72: Bug: Cannot include `S3` image in a `GitHub` issue comment
We are able to upload images to `S3` via `REST API` 🎉 
URL: https://imgup.fly.dev/api/images
Docs: https://github.com/dwyl/imgup/blob/main/api.md#4-testing-the-api-from-hoppscotch

image

```json
{
  "compressed_url": "https://s3.eu-west-3.amazonaws.com/imgup-compressed/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzhj3.jpg",
  "url": "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzhj3.jpg"
}
```

The problem is when we attempt to view one of these images directly in the browser e.g. by copy-pasting the `URL` into a new browser tab: https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzhj3.jpg 

It automatically downloads the file instead of displaying it in the browser.
I suspect this is because the MIME Type is not correctly set on `S3` ... 

This is why it does not display the image in a `GitHub` issue comment or `.md` file ...
```md
![img](https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhoFgi1PXSfoeFi9PGT3R33fpq4iAsQJRuU2Yoy7yMzhj3.jpg)
```

img

... 🤷‍♂️ 

@LuchoTurtle do you have time to investigate this? 
I've tried reading the docs: https://hexdocs.pm/ex_aws_s3/ExAws.S3.html#t:initiate_multipart_upload_opt/0 
but can't seem to find where to put the Content-Type for the uploaded file ... 🤷‍♂️

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #66 
closes #72

This fixes the black border issue on #66 and images not displaying on sites like Github, as described in #72.

The new version has already been deployed, so it works properly.
Here's an example of a compressed picture without a black border and showing properly on Github.

demo

### CODE REVIEW

File: an_aws_sam_imgup-compressor/src/index.js [hunk 1]
```diff
@@ -18,18 +18,18 @@ exports.handler = async (event) => {
     // Compress the image to a 200x200 avatar square as a buffer, without stretching
     const compressedImageBuffer = await sharp(uncompressedImage.Body)
     .resize({ 
-        width: 200, 
         height: 200, 
         fit: 'contain'
     })
+    .png()
```
Comment (nelsonic) [inline an_aws_sam_imgup-compressor/src/index.js:24]: Does conversion to `.png` have any other benefits (e.g. reduction of bandwidth) over other formats?

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle thanks for making these updates. ✅

File: an_aws_sam_imgup-compressor/src/index.js (hunk 1 above)
Comment (LuchoTurtle) [reply an_aws_sam_imgup-compressor/src/index.js:24]: Not particularly, but because I didn't strictly have access to the `content type` of the file in the `index.js` lambda function, as per https://github.com/lovell/sharp/issues/2232, I figured it would make sense to output the buffer to `png` and set the `content-type` as such when saving the file.

Comment (nelsonic) [reply an_aws_sam_imgup-compressor/src/index.js:24]: Cool. Thanks. 👌
