### PR TITLE
[PR] Addressing edge cases

### LINKED ISSUE #69: Edge cases in Upload
I've spotted some possible errors with the following code:
https://github.com/dwyl/imgup/blob/81de078da15f36430f00c6f20bc5dd9169e5e1b2/lib/app/upload.ex#L23-L28

- `{:ok, file_binary} = File.read(image.path) `
This will break if `File.read` returns an error, `{:errror, reason}` as the match will fail, see https://hexdocs.pm/elixir/1.12/File.html#read/1

- `file_cid = Cid.cid(file_binary)`
The `Cid.cid` function returns a string, however the string can represent an error: `invalid data type`, see https://hexdocs.pm/excid/Cid.html#cid/1
image

Not an error in itself but I think we can make this a bit more readable:

```elixir
file_extension = image.content_type
|> MIME.extensions()
|> List.first()

file_name = "#{file_cid}.#{file_extension}" 
```

Also `MIME.extension` can return an empty list, so in this case the file extension would be `nil`. Do you still want to upload the file if the extension is unknown? If yes maybe the file name should be just the `file_cid`
see https://hexdocs.pm/mime/MIME.html#extensions/1-examples
image

### PR DESCRIPTION
**Pull request by LuchoTurtle**
closes #69 

This adds pattern matching and returns the person meaningful error messages according to whether there was an error:
- reading the `path` from the `image`.
- creating the `CID` from the file contents.
- getting the `file extension`.
- uploading the file to `S3`.

I *had* to use `mock` to force the `request` to `S3` to fail in tests and to emulate invalid binary data so `CID` would also fail, as detailed in #69.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
This should be reviewable now 🆗

**Review by nelsonic — APPROVED** [review]
Thanks @dependabot 🤖 👌

**Comment by nelsonic** [comment]
On my localhost, ran the following:
```
git pull 
git checkout 'edge-cases-#69'
mix deps.get
source .env
mix c
```

Got:
```
  1) test upload/1 happy path REAL Upload (App.UploadTest)
     test/app/upload_test.exs:4
     Assertion with == failed
     code:  assert App.Upload.upload(image) == {:ok, expected_response}
     left:  {:error, :upload_fail}
     right: {:ok, %{compressed_url: "https://s3.eu-west-3.amazonaws.com//zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png", url: "https://s3.eu-west-3.amazonaws.com//zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png"}}
     stacktrace:
       test/app/upload_test.exs:18: (test)



  2) test upload with image keyword (AppWeb.APITest)
     test/app_web/api_test.exs:64
     ** (RuntimeError) expected response with status 200, got: 400, with body:
     "{\"errors\":{\"detail\":\"Error uploading file. There was an error uploading the file to S3.\"}}"
     code: assert Jason.decode!(response(conn, 200)) == expected
     stacktrace:
       (phoenix 1.7.6) lib/phoenix/test/conn_test.ex:373: Phoenix.ConnTest.response/2
       test/app_web/api_test.exs:74: (test)

..

  3) test upload succeeds (happy path) (AppWeb.APITest)
     test/app_web/api_test.exs:51
     ** (RuntimeError) expected response with status 200, got: 400, with body:
     "{\"errors\":{\"detail\":\"Error uploading file. There was an error uploading the file to S3.\"}}"
     code: assert Jason.decode!(response(conn, 200)) == expected
     stacktrace:
       (phoenix 1.7.6) lib/phoenix/test/conn_test.ex:373: Phoenix.ConnTest.response/2
       test/app_web/api_test.exs:61: (test)

..........
Finished in 0.2 seconds (0.1s async, 0.1s sync)
15 tests, 3 failures

Randomized with seed 654535
----------------
COV    FILE                                        LINES RELEVANT   MISSED
100.0% lib/app.ex                                      9        0        0
100.0% lib/app/repo.ex                                 5        0        0
 90.0% lib/app/upload.ex                             108       20        2
100.0% lib/app_web/components/layouts.ex               5        0        0
 90.0% lib/app_web/controllers/api_controller.e       46       10        1
 66.7% lib/app_web/controllers/api_json.ex            20        3        1
100.0% lib/app_web/controllers/page_controller.       25        5        0
100.0% lib/app_web/controllers/page_html.ex            5        0        0
100.0% lib/app_web/endpoint.ex                        48        0        0
100.0% lib/app_web/live/imgup_live.ex                 93       26        0
100.0% lib/app_web/router.ex                          30        4        0
100.0% lib/app_web/s3_upload.ex                      127       24        0
[TOTAL]  95.7%
----------------
Generating report...
Saved to: cover/
FAILED: Expected minimum coverage of 100%, got 95.7%.
```

**Comment by LuchoTurtle** [comment]
Does your `.env` file have the following format?

```dotfile
export AWS_ACCESS_KEY_ID='XXXX'
export AWS_SECRET_ACCESS_KEY='XXX'
export AWS_REGION='eu-XX-3'
export AWS_ORIGINAL_BUCKET='imgup-XX'
export AWS_COMPRESSED_BUCKET='imgup-XX'
```

**Comment by LuchoTurtle** [comment]
Nevermind.
The API is not working correctly...

image

The old problem where we need to update the secrets remotely is happening again :/

**Comment by LuchoTurtle** [comment]
It seems the bucket env variables are not being correctly loaded when deploying.

**Comment by nelsonic** [comment]
The buckets need to be set on Fly.io: https://fly.io/apps/imgup/secrets
image

The values of the Bucket Environment Variables aren't secret; they appear in the URL ... 🔗 😉 
So we don't need to obfuscate/hide them. 
Just advise people to replace them with their own values.


```
flyctl secrets set AWS_ORIGINAL_BUCKET=imgup-original -a imgup
flyctl secrets set AWS_COMPRESSED_BUCKET=imgup-compressed -a imgup
```

Updated:
image

But still getting the error:

```sh
Couldn't upload files to S3. Open an issue on Github and contact the repo owner.
```

image

as noted in: https://github.com/dwyl/imgup/issues/69#issuecomment-1620543919

**Comment by nelsonic** [comment]
With the env vars as required:
```
export AWS_ACCESS_KEY_ID=AKIAetc.
export AWS_SECRET_ACCESS_KEY=aietc.
export AWS_REGION='eu-west-3'
export AWS_ORIGINAL_BUCKET='imgup-original'
export AWS_COMPRESSED_BUCKET='imgup-compressed'
```

Still get:

```sh
mix c


  1) test upload with image keyword (AppWeb.APITest)
     test/app_web/api_test.exs:64
     Assertion with == failed
     code:  assert Jason.decode!(response(conn, 200)) == expected
     left:  %{"compressed_url" => "https://s3.eu-west-3.amazonaws.com//zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png", "url" => "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png"}
     right: %{
              "compressed_url" => "https://s3.eu-west-3.amazonaws.com/imgup-compressed/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png",
              "url" => "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png"
            }
     stacktrace:
       test/app_web/api_test.exs:74: (test)

....

  2) test upload/1 happy path REAL Upload (App.UploadTest)
     test/app/upload_test.exs:4
     Assertion with == failed
     code:  assert App.Upload.upload(image) == {:ok, expected_response}
     left:  {:ok, %{compressed_url: "https://s3.eu-west-3.amazonaws.com//zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png", url: "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png"}}
     right: {
              :ok,
              %{
                compressed_url: "https://s3.eu-west-3.amazonaws.com/imgup-compressed/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png",
                url: "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png"
              }
            }
     stacktrace:
       test/app/upload_test.exs:18: (test)



  3) test upload succeeds (happy path) (AppWeb.APITest)
     test/app_web/api_test.exs:51
     Assertion with == failed
     code:  assert Jason.decode!(response(conn, 200)) == expected
     left:  %{"compressed_url" => "https://s3.eu-west-3.amazonaws.com//zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png", "url" => "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png"}
     right: %{
              "compressed_url" => "https://s3.eu-west-3.amazonaws.com/imgup-compressed/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png",
              "url" => "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png"
            }
     stacktrace:
       test/app_web/api_test.exs:61: (test)

........
Finished in 1.2 seconds (1.1s async, 0.1s sync)
15 tests, 3 failures

Randomized with seed 88516
----------------
COV    FILE                                        LINES RELEVANT   MISSED
100.0% lib/app.ex                                      9        0        0
100.0% lib/app/repo.ex                                 5        0        0
100.0% lib/app/upload.ex                             108       20        0
100.0% lib/app_web/components/layouts.ex               5        0        0
100.0% lib/app_web/controllers/api_controller.e       46       10        0
100.0% lib/app_web/controllers/api_json.ex            20        3        0
100.0% lib/app_web/controllers/page_controller.       25        5        0
100.0% lib/app_web/controllers/page_html.ex            5        0        0
100.0% lib/app_web/endpoint.ex                        48        0        0
100.0% lib/app_web/live/imgup_live.ex                 93       26        0
100.0% lib/app_web/router.ex                          30        4        0
100.0% lib/app_web/s3_upload.ex                      127       24        0
[TOTAL] 100.0%
----------------
Generating report...
Saved to: cover/
```

The URL in the tests is:
```sh
https://s3.eu-west-3.amazonaws.com//zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png
```

The bucket is being omitted ... 😕 

https://github.com/dwyl/imgup/blob/0366a9184f404115fb3c18c17cd90eebc04aaafa/test/app_web/api_test.exs#L43C13-L48

@LuchoTurtle happy to show you this at my desk.

**Comment by LuchoTurtle** [comment]
image

This is most definitely an issue regarding env variables, which are not being correctly loaded. Perhaps restarting/redeploying might help?

**Comment by nelsonic** [comment]
Ok. We are looking at two separate (but apparently related) issues here. 
1. The tests don't pass on my `localhost`. 
2. `S3` Bucket environment variables are not set on `Fly.io`. 

I'm going to figure out `localhost` first.
I have the environment variables defined correctly. 
When I run `printenv` I see the following:

```sh
...
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_REPOSITORY=/opt/homebrew
MANPATH=/opt/homebrew/share/man::
INFOPATH=/opt/homebrew/share/info:
ANDROID_HOME=/Users/n/Library/Android/sdk
AWS_ACCESS_KEY_ID=AWS
AWS_SECRET_ACCESS_KEY=aitookourjobs
AWS_REGION=eu-west-3
AWS_ORIGINAL_BUCKET=imgup-original
AWS_COMPRESSED_BUCKET=imgup-compressed
_=/usr/bin/printenv
```

Checked the spelling on the env vars `AWS_ORIGINAL_BUCKET` 
image

and `AWS_COMPRESSED_BUCKET`: 
image

Ran: `MIX_ENV=test mix compile --force`

Got the following warning:
```sh
warning: Application.get_env/2 is discouraged in the module body, use Application.compile_env/3 instead
  lib/app/upload.ex:7: App.Upload
```

This relates to the following lines: 
https://github.com/dwyl/imgup/blob/0366a9184f404115fb3c18c17cd90eebc04aaafa/test/app_web/api_test.exs#L43C13-L48

But the Good News is that tests work on `localhost`: 

```sh
mix c
...............
Finished in 1.5 seconds (1.4s async, 0.1s sync)
15 tests, 0 failures

Randomized with seed 591967
----------------
COV    FILE                                        LINES RELEVANT   MISSED
100.0% lib/app.ex                                      9        0        0
100.0% lib/app/repo.ex                                 5        0        0
100.0% lib/app/upload.ex                             108       20        0
100.0% lib/app_web/components/layouts.ex               5        0        0
100.0% lib/app_web/controllers/api_controller.e       46       10        0
100.0% lib/app_web/controllers/api_json.ex            20        3        0
100.0% lib/app_web/controllers/page_controller.       25        5        0
100.0% lib/app_web/controllers/page_html.ex            5        0        0
100.0% lib/app_web/endpoint.ex                        48        0        0
100.0% lib/app_web/live/imgup_live.ex                 93       26        0
100.0% lib/app_web/router.ex                          30        4        0
100.0% lib/app_web/s3_upload.ex                      127       24        0
[TOTAL] 100.0%
----------------
Generating report...
Saved to: cover/
```

image

Now looking into "Part 2" on `Fly.io`.

**Comment by nelsonic** [comment]
FYI: I've renamed the two `S3 Bucket` environment variables:
```sh
AWS_COMPRESSED_BUCKET-> AWS_S3_BUCKET_ORIGINAL
AWS_COMPRESSED_BUCKET -> AWS_S3_BUCKET_COMPRESSED
```

The _reason_ is: 
1. Including the `S3` keyword in the env var makes it clear what kind of bucket we are using. Believe it or not, I've had _several_ people ask me this question in the past when using `S3` ... 🙄 So having it clear avoids those questions. 👌 
2. Putting the "variable" at the end of the variable name helps with scanning. 

I've updated the variables in the project, CI and Fly.io.

```sh
flyctl secrets set AWS_S3_BUCKET_ORIGINAL=imgup-original -a imgup
flyctl secrets set AWS_S3_BUCKET_COMPRESSED=imgup-compressed -a imgup
```
Removed the "old" ones to avoid confusion:

```sh
fly secrets unset AWS_ORIGINAL_BUCKET -a imgup
fly secrets unset AWS_COMPRESSED_BUCKET -a imgup
```

https://fly.io/apps/imgup/secrets
image


FYI: the two bucket names were not in the `README.md` Env Var section:
[https://github.com/dwyl/imgup/tree/edge-cases-%2369#2-get-your-aws-keys-and-export-as-environment-variables](https://github.com/dwyl/imgup/tree/02933e61f19b75b925f4c369f9ee49429ec180f2#2-get-your-aws-keys-and-export-as-environment-variables)
image

So added them. ✅

**Comment by nelsonic** [comment]
When I deliberately corrupt the `.jpeg` file the upload still works:
image

But the file is invalid so nothing is visible in the browser. 
We do not have a failure condition for this _real_ test. 
But we have no way of controlling for this right now.

File: lib/app/upload.ex [hunk 1]
```diff
@@ -14,53 +14,93 @@ defmodule App.Upload do
...
-    #      "expiry-date=\"Thu, 15 Jun 2023 00:00:00 GMT\", rule-id=\"delete-after-1-day\""},
-    #     {"x-amz-server-side-encryption", "AES256"},
-    #     {"Content-Type", "application/xml"},
-    #     {"Transfer-Encoding", "chunked"},
-    #     {"Server", "AmazonS3"}
-    #   ],
-    #   status_code: 200
-    # }
+        # Check if file `cid` and extension are valid.
+        case {file_cid, file_extension} do
```
Comment (nelsonic) [inline lib/app/upload.ex:32]: With these _nested_ `case` statements the complexity of this file has gone up to a `9` from a `3`. 
We don't currently have a CI check for cyclomatic complexity:
https://en.wikipedia.org/wiki/Cyclomatic_complexity

But the gist is this: if you have more than 2 nested `if`, `case` or `cond` (etc.) statements,
`then` the complexity of the function is too high and the number of branches to test becomes 6<.
This means the function needs to be split into smaller functions that are in turn easier to unit test.

Comment (LuchoTurtle) [reply lib/app/upload.ex:32]: Interesting read. I've read https://www.youtube.com/watch?v=9RvUj1Psqgk&ab_channel=iProcessConsulting to get a better overview and it makes sense. I'll refactor and split validation into different private functions.

I had initially tried to use [`with`](https://www.openmymind.net/Elixirs-With-Statement/) to improve code readability but I wasn't able to properly pattern-match the happy path.

Comment (LuchoTurtle) [reply lib/app/upload.ex:98]: I've split the functions and used `with` to make the code clearer (check [`beb03a1` (#86)](https://github.com/dwyl/imgup/pull/86/commits/beb03a1ecfe7f766f71b0d21ccef5e6fb8561c45), [`e307c4d` (#86)](https://github.com/dwyl/imgup/pull/86/commits/e307c4d3339f555430c41edca0fb361db5f7aa85), [`18af780` (#86)](https://github.com/dwyl/imgup/pull/86/commits/18af780c9612f145d3a42b4aff3fc21ea056f05f))

**Comment by LuchoTurtle** [comment]
I've included the needed changes to fix the env variable deployment issue in #88 (which unfortunately #86 #96 didn't fix). I've tested this locally and deployed it to https://imgup.fly.dev/ and it's now working, so it's assured the issue is fixed.

I've also refactored the `upload/1` function according to the feedback given.

**Comment by nelsonic** [comment]
@LuchoTurtle edge case tests for `corrupted.jpg` and `empty.jpg` pushed. I would expect the `empty.jpg` to fail ... 
But it still passes and returns the following:

```elixir
%{
   compressed_url: "https://s3.eu-west-3.amazonaws.com/imgup-compressed/zb2rhngHXWi8mR5YHX3Go4xDYpZqqcAtGefn8sktQMM7YzKEz.jpg",
   url: "https://s3.eu-west-3.amazonaws.com/imgup-original/zb2rhngHXWi8mR5YHX3Go4xDYpZqqcAtGefn8sktQMM7YzKEz.jpg"
 }
```
The image doesn't load (because it's empty):
empty

**Comment by nelsonic** [comment]
When I attempt to run the following test with an `empty.pdf` (the file has `zero bytes`):

```elixir
  test "check_file_binary_and_extension :invalid_extension_and_cid" do
    image = %Plug.Upload{
      content_type: "application/pdf",
      filename: "empty.pdf",
      path: [:code.priv_dir(:app), "static", "images", "empty.pdf"] |> Path.join()
    }
    assert App.Upload.check_file_binary_and_extension(image) == {:error, :invalid_extension}
  end
```

the result is: `:ok`

```sh
{:ok, {"zb2rhngHXWi8mR5YHX3Go4xDYpZqqcAtGefn8sktQMM7YzKEz", "pdf"}}
``` 


Or full test response:
```sh
  1) test check_file_binary_and_extension :invalid_extension_and_cid (App.UploadTest)
     test/app/upload_test.exs:78
     Assertion with == failed
     code:  assert App.Upload.check_file_binary_and_extension(image) == {:error, :invalid_extension}
     left:  {:ok, {"zb2rhngHXWi8mR5YHX3Go4xDYpZqqcAtGefn8sktQMM7YzKEz", "pdf"}}
     right: {:error, :invalid_extension}
     stacktrace:
       test/app/upload_test.exs:84: (test)
```

i.e. the `mock` is giving a **_`false`_ positive**. 
This is a **_lot_ worse** than not addressing the edge cases because it creates a `false` sense that "everything is working" when in fact it is not. 

everything fine

We are adding code to our project that is unreachable in the **_real_ world** and mocking the tests.
I don't know how `else` to say this but it's like having something that serves no purpose: 

image

**Review by nelsonic — CHANGES_REQUESTED** [review]
Please remove the mocks. 
If we cannot write a _real_ test first for code or error handling then we haven't understood the problem. 
I'm sorry if this seems "harsh" but all code that is added has to be maintained. 
If we cannot write a _real_ test for an "edge case" then the "edge case" doesn't exist.

**Comment by nelsonic** [comment]
When we add code to a project that doesn't need to be there it's like an _elaborate_ moustache:

image

It's all maintenance and zero practicality.

**Comment by nelsonic** [comment]
Very happy to return friendly error messages if the file type is invalid. That is 100% good. 
But the `check_file_binary_and_extension/1` function has several `case`es that are unreachable in practice.
So we are creating `mocks` _just_ to pretend that we're reaching them... 🙃 

image

Whenever I see this sign I think "Morons". 🤦‍♂️ 
`mocks` for unreachable code that we don't know how to test are similarly pointless.
This is why we have TDD, to only write the code that we actually _need_.

Again, no _personal_ offence intended. Just a learning opportunity.

**Comment by LuchoTurtle** [comment]
I've found that the "empty.jpg" test you've added was "failing" because the file wasn't actually empty. I've added an empty file with an `image/jpeg` content type to simulate this (along other invalid files to test different scenarios).

File: test/app_web/api_test.exs [hunk 2]
```diff
@@ -124,7 +124,7 @@ defmodule AppWeb.APITest do
            }
   end
 
-  test "empty image (meaning it has a valid content type) should return an error", %{conn: conn} do
+  test "file with invalid binary data type and extension should return error. ", %{conn: conn} do
```
Comment (LuchoTurtle) [inline test/app_web/api_test.exs:127]: This test should describe that, although the file is empty, it's still an image (`content-type` is `image/jpeg`, so the extension is not necessarily invalid.

Comment (nelsonic) [reply test/app_web/api_test.exs:127]: Thanks for fixing that test description. 👍

Comment (LuchoTurtle) [reply test/app_web/api_test.exs:127]: I didn't fix anything, I'm mentioning the change you've made here might not be correct 👀

File: api.md [hunk 3]
```diff
@@ -390,6 +391,242 @@ if you try to upload another file other than an image:
...
+
+Now let's implement the features so our tests pass! ✅
+
+Open `lib/app/upload.ex`.
+We are going to refactor this function
+so it returns specific errors 
+as the image is read all the way until it is uploaded to `S3`.
+
+```elixir
+def upload(image) do
```
Comment (nelsonic) [inline api.md:483]: @LuchoTurtle the reason I haven't reviewed/merged this PR is that there is still quite a _lot_ you haven't updated. 
E.g. this function which looks nothing like this anymore:
https://github.com/dwyl/imgup/blob/2e29f8485de432f275507658b1e05e4be3555f69/lib/app/upload.ex#L20-L59

File: lib/app/upload.ex [hunk 4]
```diff
@@ -14,53 +14,107 @@ defmodule App.Upload do
...
-      |> ExAws.S3.upload(Application.get_env(:ex_aws, :original_bucket), file_name, acl: :public_read, content_type: image.content_type )
-      |> ExAws.request(get_ex_aws_request_config_override())
+      # Fetch the contents of the returned XML string from `ex_aws`.
+      # This XML is parsed with `sweet_xml`:
+      # github.com/kbrw/sweet_xml#the-x-sigil
+      url = upload_response_body.body |> xpath(~x"//text()") |> List.to_string()
+      compressed_url = "#{@compressed_baseurl}#{file_name}"
+      {:ok, %{url: url, compressed_url: compressed_url}}
+    else
+      {:error, :failure_read} -> {:error, :failure_read}
```
Comment (nelsonic) [inline lib/app/upload.ex:53]: If you aren't going to `do` anything with these various `:error` matches, then just make it generic:
```elixir
      {:error, :failure_read} -> {:error, :failure_read}
      {:error, :invalid_extension_and_cid} -> {:error, :invalid_extension_and_cid}
      {:error, :invalid_cid} -> {:error, :invalid_cid}
      {:error, :invalid_extension} -> {:error, :invalid_extension}
      {:error, :upload_fail} -> {:error, :upload_fail}
```

Becomes:

```elixir
      {:error, reason} -> {:error, reason}
```

File: lib/app/upload.ex [hunk 5]
```diff
@@ -14,53 +14,107 @@ defmodule App.Upload do
...
+    end
+  end
+
+  defp upload_file_to_s3(file_cid, file_extension, image) do
+    # Creating filename with the retrieved extension
+    file_name = "#{file_cid}.#{file_extension}"
+
+    # Make request.
+    # Return the body of the response if successful.
+    # Otherwise, raise error.
```
Comment (nelsonic) [inline lib/app/upload.ex:67]: comment says "raise error", but this doesn't [`raise`](https://elixir-lang.org/getting-started/try-catch-and-rescue.html#reraise) anything; it simply returns `{:error, :upload_fail}` without _logging_ anything. 🤷‍♂️

File: lib/app/upload.ex [hunk 6]
```diff
@@ -14,53 +14,107 @@ defmodule App.Upload do
...
+        |> ExAws.S3.upload(Application.get_env(:ex_aws, :original_bucket), file_name,
+          acl: :public_read,
+          content_type: image.content_type
+        )
+        |> ExAws.request(get_ex_aws_request_config_override())
+
+      {:ok, {file_name, upload_response_body}}
+    rescue
+      _e ->
+        {:error, :upload_fail}
```
Comment (nelsonic) [inline lib/app/upload.ex:81]: This is _exactly_ what we want to avoid doing.
This function doesn't `log` the error so the engineers have no idea what happened.
And then masks the error to the client by defining a `:upload_fail` 
which is not an `{:error, reason}` defined by the `ExAws.S3.upload` library/function.
So when the `client` or consuming function sees this error they have _zero_ insight.

File: api.md [hunk 7]
```diff
@@ -390,6 +391,242 @@ if you try to upload another file other than an image:
...
+> **Note** 
+>
+> We are using the [`mock` ](https://github.com/jjh42/mock)
+> library so we are able to correctly test 
+> whenever `S3` is down.
+> Although using mocks *can lead to false positives*,
+> here's acceptable because we're simulating a third-party service to be down.
+
+
+We've added a test for each scenario
```
Comment (nelsonic) [inline api.md:467]: This is not a "test"; It's a _`mock`_. 
image

It might _look_ like a "test" to the untrained eye, 
but to the person that _cares_ it's **_much_ worse** than having nothing at all.

File: api.md [hunk 8]
```diff
@@ -390,6 +391,242 @@ if you try to upload another file other than an image:
 Or an image size that's too large,
 you'll get an `413 Request Entity Too Large` error.
 
+# 5. Returning meaningful errors
 
+If something *fails*, the person using the API
+will have a `JSON` body stating 
+`"Error uploading file #26"` returned.
+This type of information is not particularly *useful*.
```
Comment (nelsonic) [inline api.md:399]: having an error that has a code e.g: `#26` (in this case a line number)
that the support staff or engineers can _easily_ identify and address
is orders of magnitude more _useful_ than `{:error, :upload_fail}`.

File: api.md [hunk 9]
```diff
@@ -390,6 +391,242 @@ if you try to upload another file other than an image:
...
+
+Open `lib/app/upload.ex`.
+We are going to refactor this function
+so it returns specific errors 
+as the image is read all the way until it is uploaded to `S3`.
+
+```elixir
+def upload(image) do
+    # Create `CID` from file contents so filenames are unique
+    case File.read(image.path) do
```
Comment (nelsonic) [inline api.md:485]: @LuchoTurtle you've shifted the logic without simplifying it.
This is _worse_ than inlining it.
And without any _logging_ this code is basically a black box when debugging.

**Review by nelsonic — CHANGES_REQUESTED** [review]
I'm not happy with writing a `mock` or `code` for an unspecified `AWS S3` failure event that we cannot test for. 
It's totally fine to have a _generic_ failure event in this **_exceptionally_ unlikely event** of there being an error with `S3`.

Generally speaking, a Software product/app that calls many _external_ APIs in the "backend" 
does not expose these details to the client/consumer.
Unless the client _already_ knows those services are being used, e.g. `Google Auth` 
In the case of `S3` the image `URL` _currently_ has `S3` in the address but it _definitely_ won't for _ever_ ... 

The last `S3` outage was in 2017: https://aws.amazon.com/message/41926/
They are **_exceedingly_ rare** and if we cannot test the scenario, to all intents and purposes, it doesn't exist. 

> In the "Mars Rover" analogy: if the uplink back to `NASA HQ` is _down_ 
the lander isn't going to send a messages back to `NASA HQ` saying the channel is broken because they _already_ know and what channel would they _use_ ... 🤷‍♂️ 

If an error occurs with `S3` we just return a generic:
"Sorry uploads are not working right now, please try again later."
Or if we want to get fancy, we return a "trace ID" that allows the engineers to immediately find that request in the logs. 
See: https://www.w3.org/TR/trace-context/

We can (should) ***`log`*** the error in our infra so that _we_ know why it happened. 
And when we eventually have a "status" page we can write a quick post explaining what the root cause is so people how how we _fixed_ it.
But adding `mocks` to the project just so that we can _pretend_ to test for this [black swan event](https://en.wikipedia.org/wiki/Black_swan_theory) is not useful. 

We don't _yet_ have a "style guide" for our `Elixir` code. 
But if we did the `with` keyword and `<-` (reverse arrow) notation would definitely be on the "No" list.
They make the code terse without any real benefit other than masking complexity of implementation.

```elixir
    with {:ok, {file_cid, file_extension}} <- check_file_binary_and_extension(image),
         {:ok, {file_name, upload_response_body}} <-
           upload_file_to_s3(file_cid, file_extension, image) do
```

This is just shifting business logic into one line and requires significant time for the (human) reader to parse.
"Go do all these things and if anything fails return a bunch of errors..."
Then putting a bunch of matches for those errors:

```elixir
{:error, :failure_read} -> {:error, :failure_read}
{:error, :invalid_extension_and_cid} -> {:error, :invalid_extension_and_cid}
{:error, :invalid_cid} -> {:error, :invalid_cid}
{:error, :invalid_extension} -> {:error, :invalid_extension}
{:error, :upload_fail} -> {:error, :upload_fail}
```
If you aren't actually _doing_ anything with the error message/type, 
then just pass it straight through with a generic "reason":

```elixir
{:error, reason} -> {:error, reason}
```

Otherwise you are duplicating logic unnecessarily. 

I don't like this code at all. Because all you have done is move the complexity elsewhere. 
One of the biggest problems smart people have is they write complex code.
Code that will confuse and overwhelm a beginner.
This is _fine_ in a close source 2-person project.
But not desirable in an Open Source project where we _want_ others to read and contribute to the code.

File: lib/app_web/controllers/api_controller.ex [hunk 10]
```diff
@@ -3,23 +3,37 @@ defmodule AppWeb.ApiController do
...
+      case App.Upload.upload(params) do
+        {:ok, body} ->
+          render(conn, :success, body)
+
+        {:error, :failure_read} ->
+          render(conn |> put_status(400), %{body: "Error uploading file. Failure reading file."})
+
+        {:error, :invalid_cid} ->
+          render(conn |> put_status(400), %{
+            body: "Error uploading file. Failure creating the CID filename."
```
Comment (nelsonic) [inline lib/app_web/controllers/api_controller.ex:18]: This error message means _nothing_ to the person using the `API`. 
They don't know (_or **care**_) that we'er using `CIDs` under the hood.
This is worse than a generic error message because:
a) It doesn't log anything so we cannot debug it.
b) it returns information the `API` caller doesn't know what to _do_ with.

How does the caller of the `API` modify their request in response to this error? 🤷‍♂️

**Comment by nelsonic** [comment]
I don't want to just _close_ this PR and _waste_ both my _own_ time and Lucho's time. ⏳ 💸 🔥 
But I don't feel like _any_ of this code addresses a problem that a `person` _using_ the `API` has identified. 🤷‍♂️ 
***Yes***, we want to address _potential_ edge cases. ✅ 
We want to make the `API` helpful to the `people` using it. 🙏 
But this PR doesn't do that. 😕 
It has **_zero_ Logging** which means the engineers cannot debug errors
and returns _unhelpful_ errors that _mask_ the underlying issue.

**Comment by nelsonic** [comment]
For future reference, whenever you are tempted to put the word "and" in a function name, don't. 
`check_file_binary_and_extension` is an instant ["code smell"](https://en.wikipedia.org/wiki/Code_smell).

File: api.md [hunk 11]
```diff
@@ -390,6 +391,242 @@ if you try to upload another file other than an image:
...
+              try do
+                image.path
+                |> ExAws.S3.Upload.stream_file()
+                |> ExAws.S3.upload(Application.get_env(:ex_aws, :original_bucket), file_name,
+                  acl: :public_read,
+                  content_type: image.content_type
+                )
+                |> ExAws.request(get_ex_aws_request_config_override())
+              rescue
+                _e ->
```
Comment (nelsonic) [inline api.md:522]: just added a `Logger` line to the `upload_file_to_s3/3` function in `lib/app/upload.ex`:
https://github.com/dwyl/imgup/blob/831d2eb4cec9c20ed09b822e38a579d8ef22f6d6/lib/app/upload.ex#L79

Guess what it logs as part of the `mock` invocation ...
https://github.com/dwyl/imgup/actions/runs/5560741019/jobs/10157932627#step:7:216
image

```sh
Error: 00:35.176 request_id=F3H1G9fWV3C_m1oAAbzS [error] ** (UndefinedFunctionError) function ExAws.request/2 is undefined or private
    (ex_aws 2.4.3) ExAws.request(%ExAws.S3.Upload{src: %File.Stream{path: "/home/runner/work/imgup/imgup/_build/test/lib/app/priv/static/images/phoenix.png", modes: [:raw, :read_ahead, :binary], line_or_bytes: 5242880, raw: true}, bucket: "imgup-original", path: "zb2rhXACvyoVCaV1GF5ozeoNCXYdxcKAEWvBTpsnabo3moYwB.png", upload_id: nil, opts: [acl: :public_read, content_type: "image/png"], service: :s3}, %{})
    (app 1.0.0) lib/app/upload.ex:74: App.Upload.upload_file_to_s3/3
    (app 1.0.0) lib/app/upload.ex:26: App.Upload.upload/1
```

`UndefinedFunctionError`. 
So not only was the function not logging an error but the `mock` is a **`false` positive**. 
This is not "testing" an error on `S3`; it's _mocking_ a function call incorrectly. 

picard-double-facepalm

Comment (nelsonic) [reply api.md]: I've removed this `mock` because it doesn't add any robustness to the project. 
I've left your code 99.9% intact and only added the `Logger.error` in case there is an `S3` upload error so that we can trace and resolve it.

**Comment by nelsonic** [comment]
@LuchoTurtle I've already removed (commented out) the offending `mock` and added a valid test.
The remaining tests are all passing with 100% coverage. 
This PR is mergeable. Assign back to me once you've had a chance to tidy the section in the `README.md` 
Thanks. 👍

File: api.md (hunk 7 above)
Comment (LuchoTurtle) [reply api.md:553]: Given that `mocks` were deleted, this is fixed 👌

File: lib/app_web/controllers/api_controller.ex (hunk 10 above)
Comment (LuchoTurtle) [reply lib/app_web/controllers/api_controller.ex]: I've made the changes for adding logging and returning information only on the relevant scenarios where the person can change (no file content, invalid content type, empty image files).

Given that you've made the changes for the relevant pattern matches to be returned to the person in [`ef113ec` (#86)](https://github.com/dwyl/imgup/pull/86/commits/ef113ec4d749fe0744909d5d8c74d538c5acccfe), I'm marking this as resolved as well.

**Comment by LuchoTurtle** [comment]
I've made some changes, namely:
- added logging.
- added tests for invalid content type.
- changed API error messages that are relevant to the user, and defaulted unlikely scenarios (such as `S3` being down) to displaying a generic message.

I didn't change "code smells" like `check_file_binary_and_extension` since you want to get this merged ASAP and that would entail more time spend reviewing.
Granted, although I understand your statements about not wanting to use `with` statements and avoiding nested `case` statements that capture these edge cases, I don't know how to "simplify" the code that will, simultaneously:
- log each scenario so we know what exactly went wrong.
- *not* use nested cases without containing logic in functions

Perhaps my Elixir syntax skills are lacking but I don't know how to make the code more readable and simpler without doing these.

Assigning back to you, I've made the changes according to the feedback and commented on those that were affected.

File: api.md (hunk 8 above)
Comment (LuchoTurtle) [reply api.md]: I've added logging and pattern-matched the relevant information, all the while being compatible with the other feedback you've given (showing a generic error message to the person).

File: api.md (hunk 9 above)
Comment (LuchoTurtle) [reply api.md:587]: Added comment on this in https://github.com/dwyl/imgup/pull/86#issuecomment-1637946116.

**Review by nelsonic — APPROVED** [review]
Thanks @LuchoTurtle 👌 
All good enhancements. ✅ 
Hopefully we can focus on features requested by `people` _using_ the product. 🤞

**Comment by LuchoTurtle** [comment]
@nelsonic working on #87 because of merge conflicts and trying to remove `Mock`, fyi

**Comment by nelsonic** [comment]
Cool. Thanks.
